/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransformRouteImport } from './routes/transform'
import { Route as SpanRouteImport } from './routes/span'
import { Route as IndexRouteImport } from './routes/index'

const TransformRoute = TransformRouteImport.update({
  id: '/transform',
  path: '/transform',
  getParentRoute: () => rootRouteImport,
} as any)
const SpanRoute = SpanRouteImport.update({
  id: '/span',
  path: '/span',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/span': typeof SpanRoute
  '/transform': typeof TransformRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/span': typeof SpanRoute
  '/transform': typeof TransformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/span': typeof SpanRoute
  '/transform': typeof TransformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/span' | '/transform'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/span' | '/transform'
  id: '__root__' | '/' | '/span' | '/transform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpanRoute: typeof SpanRoute
  TransformRoute: typeof TransformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transform': {
      id: '/transform'
      path: '/transform'
      fullPath: '/transform'
      preLoaderRoute: typeof TransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/span': {
      id: '/span'
      path: '/span'
      fullPath: '/span'
      preLoaderRoute: typeof SpanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpanRoute: SpanRoute,
  TransformRoute: TransformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
