/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransformRouteImport } from './routes/transform'
import { Route as StandardMatrixRouteImport } from './routes/standard-matrix'
import { Route as SpanRouteImport } from './routes/span'
import { Route as RangeRouteImport } from './routes/range'
import { Route as MultiplyRouteImport } from './routes/multiply'
import { Route as LinearityRouteImport } from './routes/linearity'
import { Route as InvertibilityRouteImport } from './routes/invertibility'
import { Route as EliminationRouteImport } from './routes/elimination'
import { Route as DeterminantRouteImport } from './routes/determinant'
import { Route as CompositionRouteImport } from './routes/composition'
import { Route as IndexRouteImport } from './routes/index'

const TransformRoute = TransformRouteImport.update({
  id: '/transform',
  path: '/transform',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardMatrixRoute = StandardMatrixRouteImport.update({
  id: '/standard-matrix',
  path: '/standard-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const SpanRoute = SpanRouteImport.update({
  id: '/span',
  path: '/span',
  getParentRoute: () => rootRouteImport,
} as any)
const RangeRoute = RangeRouteImport.update({
  id: '/range',
  path: '/range',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplyRoute = MultiplyRouteImport.update({
  id: '/multiply',
  path: '/multiply',
  getParentRoute: () => rootRouteImport,
} as any)
const LinearityRoute = LinearityRouteImport.update({
  id: '/linearity',
  path: '/linearity',
  getParentRoute: () => rootRouteImport,
} as any)
const InvertibilityRoute = InvertibilityRouteImport.update({
  id: '/invertibility',
  path: '/invertibility',
  getParentRoute: () => rootRouteImport,
} as any)
const EliminationRoute = EliminationRouteImport.update({
  id: '/elimination',
  path: '/elimination',
  getParentRoute: () => rootRouteImport,
} as any)
const DeterminantRoute = DeterminantRouteImport.update({
  id: '/determinant',
  path: '/determinant',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositionRoute = CompositionRouteImport.update({
  id: '/composition',
  path: '/composition',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/composition': typeof CompositionRoute
  '/determinant': typeof DeterminantRoute
  '/elimination': typeof EliminationRoute
  '/invertibility': typeof InvertibilityRoute
  '/linearity': typeof LinearityRoute
  '/multiply': typeof MultiplyRoute
  '/range': typeof RangeRoute
  '/span': typeof SpanRoute
  '/standard-matrix': typeof StandardMatrixRoute
  '/transform': typeof TransformRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/composition': typeof CompositionRoute
  '/determinant': typeof DeterminantRoute
  '/elimination': typeof EliminationRoute
  '/invertibility': typeof InvertibilityRoute
  '/linearity': typeof LinearityRoute
  '/multiply': typeof MultiplyRoute
  '/range': typeof RangeRoute
  '/span': typeof SpanRoute
  '/standard-matrix': typeof StandardMatrixRoute
  '/transform': typeof TransformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/composition': typeof CompositionRoute
  '/determinant': typeof DeterminantRoute
  '/elimination': typeof EliminationRoute
  '/invertibility': typeof InvertibilityRoute
  '/linearity': typeof LinearityRoute
  '/multiply': typeof MultiplyRoute
  '/range': typeof RangeRoute
  '/span': typeof SpanRoute
  '/standard-matrix': typeof StandardMatrixRoute
  '/transform': typeof TransformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/composition'
    | '/determinant'
    | '/elimination'
    | '/invertibility'
    | '/linearity'
    | '/multiply'
    | '/range'
    | '/span'
    | '/standard-matrix'
    | '/transform'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/composition'
    | '/determinant'
    | '/elimination'
    | '/invertibility'
    | '/linearity'
    | '/multiply'
    | '/range'
    | '/span'
    | '/standard-matrix'
    | '/transform'
  id:
    | '__root__'
    | '/'
    | '/composition'
    | '/determinant'
    | '/elimination'
    | '/invertibility'
    | '/linearity'
    | '/multiply'
    | '/range'
    | '/span'
    | '/standard-matrix'
    | '/transform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompositionRoute: typeof CompositionRoute
  DeterminantRoute: typeof DeterminantRoute
  EliminationRoute: typeof EliminationRoute
  InvertibilityRoute: typeof InvertibilityRoute
  LinearityRoute: typeof LinearityRoute
  MultiplyRoute: typeof MultiplyRoute
  RangeRoute: typeof RangeRoute
  SpanRoute: typeof SpanRoute
  StandardMatrixRoute: typeof StandardMatrixRoute
  TransformRoute: typeof TransformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transform': {
      id: '/transform'
      path: '/transform'
      fullPath: '/transform'
      preLoaderRoute: typeof TransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard-matrix': {
      id: '/standard-matrix'
      path: '/standard-matrix'
      fullPath: '/standard-matrix'
      preLoaderRoute: typeof StandardMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/span': {
      id: '/span'
      path: '/span'
      fullPath: '/span'
      preLoaderRoute: typeof SpanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/range': {
      id: '/range'
      path: '/range'
      fullPath: '/range'
      preLoaderRoute: typeof RangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiply': {
      id: '/multiply'
      path: '/multiply'
      fullPath: '/multiply'
      preLoaderRoute: typeof MultiplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linearity': {
      id: '/linearity'
      path: '/linearity'
      fullPath: '/linearity'
      preLoaderRoute: typeof LinearityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invertibility': {
      id: '/invertibility'
      path: '/invertibility'
      fullPath: '/invertibility'
      preLoaderRoute: typeof InvertibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elimination': {
      id: '/elimination'
      path: '/elimination'
      fullPath: '/elimination'
      preLoaderRoute: typeof EliminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/determinant': {
      id: '/determinant'
      path: '/determinant'
      fullPath: '/determinant'
      preLoaderRoute: typeof DeterminantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composition': {
      id: '/composition'
      path: '/composition'
      fullPath: '/composition'
      preLoaderRoute: typeof CompositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompositionRoute: CompositionRoute,
  DeterminantRoute: DeterminantRoute,
  EliminationRoute: EliminationRoute,
  InvertibilityRoute: InvertibilityRoute,
  LinearityRoute: LinearityRoute,
  MultiplyRoute: MultiplyRoute,
  RangeRoute: RangeRoute,
  SpanRoute: SpanRoute,
  StandardMatrixRoute: StandardMatrixRoute,
  TransformRoute: TransformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
